- name: Check systemd existence as Docker Guest
  stat:
    path: /bin/systemctl
  when: ansible_virtualization_role is defined and ansible_virtualization_type == "docker" and ansible_virtualization_role == "guest"
  register: docker_stat_result

# Run the service_facts module so we can detect e.g. systemd
# `service-name@.service` definitions. Specifically for finding
# `openvpn-server@.service` in RedHat-family systems.
- name: Populate service facts
  service_facts:

- name: Set systemd openvpn service name
  set_fact:
    openvpn_service_name: "openvpn@{{openvpn_config_file}}.service"
  when: '"openvpn@.service" in ansible_facts.services or (docker_stat_result.stat is defined and docker_stat_result.stat.exists == True)'

# Fedora/CentOS/RHEL separate OpenVPN into client and server
- name: Set RedHat OS family service name
  set_fact:
    openvpn_service_name: "openvpn-server@{{openvpn_config_file}}.service"
  when: ansible_os_family == "RedHat" and "openvpn-server@.service" in ansible_facts.services

- name: Set RedHat OS family OpenVPN base path
  set_fact:
    openvpn_base_dir: "/etc/openvpn/server"
  when: ansible_os_family == "RedHat" and "openvpn-server@.service" in ansible_facts.services
